<?php
use CRM_Civimyob_ExtensionUtil as E;

return array(
  'myob_api_key' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_api_key',
    'type' => 'String',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('API Key'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Application API key'),
    'help_text' => E::ts('Application API key'),
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'myob_api_secret' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_api_secret',
    'type' => 'String',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('API Secret'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Application API Secret'),
    'help_text' => E::ts('Application API Secret'),
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'myob_redirect_uri' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_redirect_uri',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Redirect Uri'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Application Redirect Uri'),
    'help_text' => E::ts('Application Redirect Uri'),
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
      'readonly' => 1,
    ),
    'quick_form_type' => 'Element',
  ),
  'myob_is_sandbox' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_is_sandbox',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '4.7',
    'title' => 'Is Sandbox ?',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Select Yes if You\'re configuring a Sandbox account.',
    'help_text' => 'Select Yes if You\'re configuring a Sandbox account.',
  ),
  'myob_login_type' => array(
    'group_name' => E::ts('MYOB Login Type'),
    'group' => 'civimyob',
    'name' => 'myob_login_type',
    'type' => 'String',
    'add' => '4.7',
    'title' => 'Cloud File Login Type',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Select the correct cloud file login type.',
    'help_text' => 'Select the correct cloud file login type.',
    'pseudoconstant' => array(
      'callback' => 'CRM_Civimyob_Form_Settings::getLoginTypeOptions',
    ),
  ),
  'myob_access_token' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_access_token',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Access Token'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_refresh_token' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_refresh_token',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Refresh Token'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_token_expiry' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_token_expiry',
    'type' => 'Date',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Token expiry date & time'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_companies_list_json' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_companies_list_json',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Companies list JSON'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_selected_company_json' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_selected_company_json',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Selected Company JSON'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_selected_company_id' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_selected_company_id',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Selected Company ID'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_taxcodes_list_json' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_taxcodes_list_json',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('TaxCodes list JSON'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_selected_taxcode_json' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_selected_taxcode_json',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Selected TaxCode JSON'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_selected_freighttaxcode_json' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_selected_freighttaxcode_json',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Selected FreightTaxCode JSON'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_selected_taxcode_id' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_selected_taxcode_id',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Selected Tax Code ID'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_selected_freighttaxcode_id' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_selected_freighttaxcode_id',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Selected Freight Tax Code ID'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
  'myob_selected_account_id' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_selected_account_id',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Selected Account ID'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Select the income account to be used in invoices.',
    'help_text' => 'Select the income account to be used in invoices.',
  ),
  'myob_accounts_list_json' => array(
    'group_name' => E::ts('MYOB Settings'),
    'group' => 'civimyob',
    'name' => 'myob_accounts_list_json',
    'type' => 'Text',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Accounts list JSON'),
    'is_domain' => 1,
    'is_contact' => 0,
  ),
);
